services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - ci_net

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
    networks:
      - ci_net

  firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium_firefox
    shm_size: 2gb
    ports:
      - "4445:4444"
    networks:
      - ci_net

volumes:
  jenkins_home:

networks:
  ci_net:
